version: '3.8'

services:
  database:
    image: postgres
    restart: always
    container_name: database
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
    ports:
      - "5234:5432"
